server:
  port: 8082

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yg_colleges
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
